"""add language to posts


Revision ID: 311af0667abe
Revises: e726857f428d
Create Date: 2022-12-29 23:21:00.004123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311af0667abe'
down_revision = 'e726857f428d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
